[package]
name = "mytemplate"
version = "0.1.0"
edition = "2021"
authors = ["ChimeWu<wujicheng0215@outlook.com>"]
license = "MIT"

[dependencies]
leptos = { version = "0.6.12", features = ["csr", "nightly"] }
